version: '3.8'

services:
  hanzo-painter:
    image: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
    container_name: hanzo-painter
    ports:
      - "${COMFYUI_PORT:-8188}:8188"
    volumes:
      - ./ComfyUI:/app/ComfyUI
      - ./input:/app/ComfyUI/input
      - ./output:/app/ComfyUI/output
      - ./models:/app/ComfyUI/models
      - ./workflows:/app/ComfyUI/workflows
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    working_dir: /app/ComfyUI
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y python3 python3-pip git wget ffmpeg &&
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 &&
        pip3 install -r requirements.txt &&
        python3 main.py --listen 0.0.0.0 --port 8188
      "
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  default:
    name: hanzo-painter-network
