name: Quick Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  quick-test:
    name: Quick Test Suite
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r tests/requirements.txt

    - name: Run tests
      run: |
        python -m pytest -v --tb=short
